name: release
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {} # support manual runs
jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.14.0
        with:
          github_token: ${{ github.token }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Configure GPG signing & publish
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          if [ -z "$GPG_PASSPHRASE" ]
          then
            echo "\GPG_PASSPHRASE is empty"
          else
            echo "\GPG_PASSPHRASE is NOT empty"
          fi
          
          if [ -z "$GPG_KEY_NAME" ]
          then
            echo "\GPG_KEY_NAME is empty"
          else
            echo "\GPG_KEY_NAME is NOT empty"
          fi

          if [ -z "$GPG_PASSPHRASE" ]
          then
            echo "\GPG_PASSPHRASE is empty"
          else
            echo "\GPG_PASSPHRASE is NOT empty"
          fi

          if [ -z "$SONATYPE_USER" ]
          then
            echo "\SONATYPE_USER is empty"
          else
            echo "\SONATYPE_USER is NOT empty"
          fi
          
          if [ -z "$SONATYPE_PASSWORD" ]
          then
            echo "\SONATYPE_PASSWORD is empty"
          else
            echo "\SONATYPE_PASSWORD is NOT empty"
          fi